"""Investment Research & Portfolio Analytics Workbench -- Streamlit app.

A research and analytics demo, not a trading system. All data is synthetic.
Nothing here is investment advice or a real market view.
"""
from __future__ import annotations

import dataclasses
import subprocess
import sys
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.analytics_pipeline import (
    load_processed_tables, run_dcf_for_all_companies, comps_valuation_summary,
    build_factor_screen, build_default_portfolios,
    compute_portfolio_analytics, build_dcf_assumptions_from_financials,
    dcf_scenarios_for_ticker, reit_scenarios_for_ticker,
    reit_cap_rate_sensitivity_for_ticker, portfolio_valuation_scenario_impact,
    portfolio_sector_shock_impact, build_research_note_inputs, PEER_GROUP_MAP,
)
from src.valuation import run_dcf, dcf_sensitivity, reit_nav, reit_cap_rate_check
from src.portfolio import validate_weights, WeightValidationError, security_concentration
from src.scenarios import Scenario, BULL, BASE, BEAR, apply_scenario_to_dcf, apply_scenario_to_reit
from src.screen import DEFAULT_FACTOR_WEIGHTS, render_research_note

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
OUTPUT_DIR = PROJECT_ROOT / "output"

st.set_page_config(page_title="Investment Research & Portfolio Analytics Workbench", layout="wide")

DISCLAIMER = (
    "**Simulated analysis.** This workbench runs entirely on synthetic data generated by "
    "this project. It is a research and analytics demo, not a trading system, not live market "
    "data, and not investment advice."
)


# --------------------------------------------------------------------------
# Data loading
# --------------------------------------------------------------------------
@st.cache_data
def _load_processed(_cache_bust: float):
    return load_processed_tables()


DB_PATH = PROCESSED_DIR / "research.db"


def data_available() -> bool:
    return DB_PATH.exists()


def get_processed():
    mtime = DB_PATH.stat().st_mtime
    return _load_processed(mtime)


@st.cache_data
def _cached_factor_screen(_cache_bust: float, weights_tuple: tuple):
    processed = get_processed()
    weights = dict(weights_tuple)
    return build_factor_screen(processed, weights)


def run_pipeline_now():
    with st.spinner("Running the pipeline (generate -> ingest -> valuation -> Excel pack)..."):
        result = subprocess.run([sys.executable, str(PROJECT_ROOT / "scripts" / "run_pipeline.py")], cwd=PROJECT_ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        st.error("Pipeline failed:\n\n" + result.stderr[-3000:])
    else:
        st.success("Pipeline complete.")
        st.cache_data.clear()
        st.rerun()


if not data_available():
    st.title("Investment Research & Portfolio Analytics Workbench")
    st.warning(
        "No processed data found yet. Run the pipeline first:\n\n"
        "```bash\npython scripts/run_pipeline.py\n```\n\n"
        "or click the button below to run it now."
    )
    if st.button("Run pipeline now", type="primary"):
        run_pipeline_now()
    st.stop()

processed = get_processed()
master = processed["security_master"]
annual = processed["company_financials_annual"]
reit_annual = processed["reit_financials_annual"]
peers = processed["peer_multiples"]
prices = processed["market_prices"].copy()
prices["date"] = pd.to_datetime(prices["date"])
events = processed["company_events"]
dq = processed["data_quality"]

REIT_TICKERS = set(master[master["security_type"] == "REIT"]["ticker"])
LATEST_YEAR = int(annual["fiscal_year"].max())
DQ_COUNTS = dq.groupby("ticker").size() if not dq.empty else pd.Series(dtype=int)


# --------------------------------------------------------------------------
# Sidebar navigation
# --------------------------------------------------------------------------
st.sidebar.title("Workbench")
view = st.sidebar.radio(
    "View",
    ["Research Universe", "Security Deep Dive", "REIT Analysis", "Portfolio Lab", "Scenario Lab"],
)
st.sidebar.markdown("---")
st.sidebar.caption(DISCLAIMER)
st.sidebar.markdown("---")
if st.sidebar.button("Re-run pipeline"):
    run_pipeline_now()


def price_chart(ticker: str, extra_ticker: str | None = None) -> go.Figure:
    sub = prices[prices["ticker"] == ticker].sort_values("date")
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=sub["date"], y=sub["price"], name=ticker, mode="lines"))
    if extra_ticker:
        sub2 = prices[prices["ticker"] == extra_ticker].sort_values("date")
        rebased = sub2["price"] / sub2["price"].iloc[0] * sub["price"].iloc[0]
        fig.add_trace(go.Scatter(x=sub2["date"], y=rebased, name=f"{extra_ticker} (rebased)", mode="lines", line=dict(dash="dot")))
    fig.update_layout(title=f"{ticker} Monthly Price (synthetic)", xaxis_title="Date", yaxis_title="Price", height=350, margin=dict(t=40))
    return fig


# --------------------------------------------------------------------------
# View 1: Research Universe
# --------------------------------------------------------------------------
if view == "Research Universe":
    st.title("Research Universe")
    st.caption(DISCLAIMER)

    st.sidebar.markdown("### Filters")
    sectors = st.sidebar.multiselect("Sector", sorted(master["sector"].unique()))
    sec_types = st.sidebar.multiselect("Security type", sorted(master["security_type"].unique()))
    countries = st.sidebar.multiselect("Country", sorted(master["country"].unique()))
    min_score = st.sidebar.slider("Minimum composite factor score", -3.0, 3.0, -3.0, 0.1)

    st.sidebar.markdown("### Factor weights")
    st.sidebar.caption("Adjust and the ranking below updates live.")
    weights = {}
    for factor, default in DEFAULT_FACTOR_WEIGHTS.items():
        weights[factor] = st.sidebar.slider(factor.replace("_", " ").title(), 0.0, 1.0, float(default), 0.05)

    mtime = DB_PATH.stat().st_mtime
    screen = _cached_factor_screen(mtime, tuple(sorted(weights.items())))

    display = screen.merge(master[["ticker", "name", "country"]], on="ticker")
    latest_prices = annual[annual["fiscal_year"] == LATEST_YEAR].set_index("ticker")["share_price"]
    display["current_price"] = display["ticker"].map(latest_prices)
    display["dq_flags"] = display["ticker"].map(DQ_COUNTS).fillna(0).astype(int)

    if sectors:
        display = display[display["sector"].isin(sectors)]
    if sec_types:
        display = display[display["security_type"].isin(sec_types)]
    if countries:
        display = display[display["country"].isin(countries)]
    display = display[display["composite_score"] >= min_score]

    cols = [
        "rank", "ticker", "name", "sector", "security_type", "country", "current_price",
        "composite_score", "valuation_discount_zscore", "growth_zscore", "leverage_zscore",
        "profitability_zscore", "momentum_zscore", "dividend_yield_zscore", "dq_flags",
    ]
    st.dataframe(
        display[cols].sort_values("composite_score", ascending=False).style.format(
            {c: "{:.2f}" for c in cols if c.endswith("zscore") or c == "composite_score"}
            | {"current_price": "{:.2f}"}
        ).background_gradient(subset=["composite_score"], cmap="RdYlGn"),
        use_container_width=True, height=560,
    )
    if (display["dq_flags"] > 0).any():
        st.caption("dq_flags = number of data-quality issues detected for that ticker (see Data Quality sheet in the Excel pack for details). Flags live on quarterly financials and do not affect the annual figures shown here.")
    st.caption(f"{len(display)} of {len(master)} securities shown.")


# --------------------------------------------------------------------------
# View 2: Security Deep Dive
# --------------------------------------------------------------------------
elif view == "Security Deep Dive":
    st.title("Security Deep Dive")
    st.caption(DISCLAIMER)

    ticker = st.selectbox("Security", sorted(master["ticker"]), index=0)
    sec = master[master["ticker"] == ticker].iloc[0]
    is_reit = ticker in REIT_TICKERS

    st.subheader(f"{sec['name']} ({ticker})")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Sector", sec["sector"])
    c2.metric("Type", sec["security_type"])
    c3.metric("Country", sec["country"])
    latest_row = annual[(annual["ticker"] == ticker) & (annual["fiscal_year"] == LATEST_YEAR)].iloc[0]
    c4.metric("Current price", f"{latest_row['share_price']:.2f}")

    tab_fin, tab_val, tab_peer, tab_price, tab_note = st.tabs(
        ["Financial History", "Valuation", "Peer Comparison", "Price Chart", "Research Note"]
    )

    with tab_fin:
        hist = annual[annual["ticker"] == ticker].sort_values("fiscal_year")
        fig = go.Figure()
        fig.add_trace(go.Bar(x=hist["fiscal_year"], y=hist["revenue_mm"], name="Revenue"))
        fig.add_trace(go.Bar(x=hist["fiscal_year"], y=hist["ebitda_mm"], name="EBITDA"))
        fig.add_trace(go.Bar(x=hist["fiscal_year"], y=hist["net_income_mm"], name="Net income"))
        fig.update_layout(barmode="group", title="Annual financials ($mm)", height=380, margin=dict(t=40))
        st.plotly_chart(fig, use_container_width=True)
        st.dataframe(hist.set_index("fiscal_year"), use_container_width=True)
        if is_reit:
            rhist = reit_annual[reit_annual["ticker"] == ticker].sort_values("fiscal_year")
            st.markdown("**REIT-specific history**")
            st.dataframe(rhist.set_index("fiscal_year"), use_container_width=True)

    with tab_val:
        if is_reit:
            st.markdown("#### REIT NAV & Capitalization-Rate Cross-Check")
            rrow = reit_annual[reit_annual["ticker"] == ticker].sort_values("fiscal_year").iloc[-1]
            nav = reit_nav(rrow["property_value_mm"], rrow["net_debt_mm"], rrow["shares_outstanding_mm"])
            cap_check = reit_cap_rate_check(rrow["noi_mm"], rrow["property_value_mm"], reference_cap_rate=rrow["cap_rate"])
            c1, c2, c3 = st.columns(3)
            c1.metric("NAV per share", f"{nav.nav_per_share:.2f}")
            c2.metric("Implied cap rate (from NOI)", f"{cap_check.implied_cap_rate:.2%}")
            c3.metric("Reported cap rate", f"{rrow['cap_rate']:.2%}")
            st.caption("NAV = property value - net debt, divided by shares outstanding. Implied cap rate = NOI / property value; cross-checked against the reported cap rate.")

            st.markdown("#### Sensitivity: NAV/share -- cap rate x NOI growth")
            sens = reit_cap_rate_sensitivity_for_ticker(ticker, reit_annual)
            sens_display = sens.copy()
            sens_display.index = [f"{i:.2%}" for i in sens.index]
            sens_display.columns = [f"{c:+.1%}" for c in sens.columns]
            st.dataframe(sens_display.style.format("{:.2f}").background_gradient(cmap="RdYlGn", axis=None), use_container_width=True)
            st.caption("DCF-style enterprise valuation does not apply to REITs -- shown as N/A. See Company Deep Dive valuation methodology in the README.")
        else:
            st.markdown("#### DCF -- editable assumptions")
            base = build_dcf_assumptions_from_financials(ticker, master, annual)
            colA, colB, colC = st.columns(3)
            revenue_growth = colA.slider("Revenue growth (Y1, applied flat)", -0.10, 0.30, float(base.revenue_growth[0]), 0.01, key=f"rg_{ticker}")
            ebitda_margin = colB.slider("EBITDA margin", 0.05, 0.60, float(base.ebitda_margin[0]), 0.01, key=f"em_{ticker}")
            discount_rate = colC.slider("Discount rate (WACC)", 0.04, 0.20, float(base.discount_rate), 0.005, key=f"dr_{ticker}")
            colD, colE, colF = st.columns(3)
            terminal_growth = colD.slider("Terminal growth", 0.0, min(0.05, discount_rate - 0.005), float(min(base.terminal_growth, discount_rate - 0.005)), 0.0025, key=f"tg_{ticker}")
            tax_rate = colE.slider("Tax rate", 0.10, 0.35, float(base.tax_rate), 0.01, key=f"tax_{ticker}")
            projection_years = colF.slider("Projection years", 3, 10, base.projection_years, 1, key=f"py_{ticker}")

            live = dataclasses.replace(
                base, revenue_growth=[revenue_growth] * projection_years, ebitda_margin=[ebitda_margin] * projection_years,
                discount_rate=discount_rate, terminal_growth=terminal_growth, tax_rate=tax_rate, projection_years=projection_years,
            )
            result = run_dcf(live)
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Enterprise value ($mm)", f"{result.enterprise_value:,.1f}")
            c2.metric("Equity value ($mm)", f"{result.equity_value:,.1f}")
            c3.metric("Value per share", f"{result.value_per_share:.2f}")
            upside = result.value_per_share / latest_row["share_price"] - 1
            c4.metric("Upside vs. current price", f"{upside:+.1%}")

            st.markdown("**Cash flow trail**")
            st.dataframe(result.cash_flow_trail.set_index("year"), use_container_width=True)

            st.markdown("#### Sensitivity: value/share -- discount rate x terminal growth")
            sens = dcf_sensitivity(
                live,
                [round(discount_rate + d, 4) for d in (-0.02, -0.01, 0.0, 0.01, 0.02)],
                [round(max(terminal_growth + d, 0.0), 4) for d in (-0.01, -0.005, 0.0, 0.005, 0.01)],
            )
            sens_display = sens.copy()
            sens_display.index = [f"{i:.2%}" for i in sens.index]
            sens_display.columns = [f"{c:.2%}" for c in sens.columns]
            st.dataframe(sens_display.style.format("{:.2f}").background_gradient(cmap="RdYlGn", axis=None), use_container_width=True)
            st.caption("Rows: discount rate. Columns: terminal growth. Recomputed live from the sliders above.")

    with tab_peer:
        peer_group = PEER_GROUP_MAP[sec["security_type"]]
        peers_latest = peers[peers["fiscal_year"] == LATEST_YEAR].copy()
        peers_latest["peer_group"] = peers_latest["security_type"].map(PEER_GROUP_MAP)
        group_peers = peers_latest[peers_latest["peer_group"] == peer_group]
        st.markdown(f"**Peer group: {peer_group}** ({len(group_peers) - 1} peers excluding {ticker})")
        st.dataframe(group_peers.drop(columns=["peer_group"]).set_index("ticker"), use_container_width=True)
        comps = comps_valuation_summary(master, annual, peers)
        comp_row = comps[comps["ticker"] == ticker]
        if not comp_row.empty:
            st.metric("Comps-implied value/share", f"{comp_row['implied_value_per_share'].iloc[0]:.2f}")

    with tab_price:
        st.plotly_chart(price_chart(ticker), use_container_width=True)
        ticker_events = events[events["ticker"] == ticker].sort_values("event_date", ascending=False)
        st.markdown("**Recent synthetic events**")
        st.dataframe(ticker_events[["event_date", "event_type", "description"]], use_container_width=True, height=250)

    with tab_note:
        dcf_all = run_dcf_for_all_companies(master, annual) if not is_reit else None
        comps = comps_valuation_summary(master, annual, peers)
        screen = build_factor_screen(processed)
        if is_reit:
            rrow = reit_annual[reit_annual["ticker"] == ticker].sort_values("fiscal_year").iloc[-1]
            scen = reit_scenarios_for_ticker(ticker, reit_annual)
            nav = reit_nav(rrow["property_value_mm"], rrow["net_debt_mm"], rrow["shares_outstanding_mm"])
            scen_vals = scen.set_index("scenario")["nav_per_share"]
            rank_row = screen[screen["ticker"] == ticker].iloc[0]
            from src.screen import ResearchNoteInputs
            note_inputs = ResearchNoteInputs(
                ticker=ticker, name=sec["name"], sector=sec["sector"], security_type=sec["security_type"],
                country=sec["country"], latest_price=float(latest_row["share_price"]),
                dcf_value_per_share=nav.nav_per_share, comp_value_per_share=float(comps[comps["ticker"] == ticker]["implied_value_per_share"].iloc[0]) if not comps[comps["ticker"] == ticker].empty else float("nan"),
                bull_value_per_share=float(scen_vals.get("Bull", float("nan"))), base_value_per_share=float(scen_vals.get("Base", float("nan"))),
                bear_value_per_share=float(scen_vals.get("Bear", float("nan"))),
                key_assumptions={"NAV method": "property value - net debt, / shares outstanding", "Reported cap rate": f"{rrow['cap_rate']:.2%}"},
                catalysts=[f"{r['event_date']}: {r['description']}" for _, r in events[(events['ticker'] == ticker) & (events['event_type'].isin(['Guidance Change', 'Acquisition']))].head(3).iterrows()],
                risks=["REIT valuations are sensitive to cap-rate assumptions; a rate shock materially changes NAV.", "All financials and prices are synthetic."],
                factor_rank=int(rank_row["rank"]), factor_total=len(screen),
                primary_valuation_method="NAV (base case)",
            )
        else:
            dcf_scenarios = dcf_scenarios_for_ticker(ticker, master, annual)
            note_inputs = build_research_note_inputs(ticker, processed, dcf_all, comps, dcf_scenarios, screen)
        st.markdown(render_research_note(note_inputs))


# --------------------------------------------------------------------------
# View 3: REIT Analysis
# --------------------------------------------------------------------------
elif view == "REIT Analysis":
    st.title("REIT Analysis")
    st.caption(DISCLAIMER)

    reit_ticker = st.selectbox("REIT", sorted(REIT_TICKERS))
    sec = master[master["ticker"] == reit_ticker].iloc[0]
    hist = reit_annual[reit_annual["ticker"] == reit_ticker].sort_values("fiscal_year")
    latest = hist.iloc[-1]

    st.subheader(f"{sec['name']} ({reit_ticker}) -- {sec['sector']}")
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Occupancy", f"{latest['occupancy_pct']:.1%}")
    c2.metric("NOI ($mm)", f"{latest['noi_mm']:.1f}")
    c3.metric("FFO ($mm)", f"{latest['ffo_mm']:.1f}")
    c4.metric("AFFO ($mm)", f"{latest['affo_mm']:.1f}")
    c5.metric("Cap rate", f"{latest['cap_rate']:.2%}")

    nav = reit_nav(latest["property_value_mm"], latest["net_debt_mm"], latest["shares_outstanding_mm"])
    leverage = latest["net_debt_mm"] / latest["property_value_mm"]
    c1, c2, c3 = st.columns(3)
    c1.metric("NAV per share", f"{nav.nav_per_share:.2f}")
    c2.metric("Leverage (net debt / property value)", f"{leverage:.1%}")
    c3.metric("Property value ($mm)", f"{latest['property_value_mm']:,.0f}")

    st.markdown("#### History")
    fig = go.Figure()
    for col, label in [("noi_mm", "NOI"), ("ffo_mm", "FFO"), ("affo_mm", "AFFO")]:
        fig.add_trace(go.Bar(x=hist["fiscal_year"], y=hist[col], name=label))
    fig.update_layout(barmode="group", title="NOI / FFO / AFFO ($mm)", height=350, margin=dict(t=40))
    st.plotly_chart(fig, use_container_width=True)
    st.dataframe(hist.set_index("fiscal_year"), use_container_width=True)

    st.markdown("#### Peer Comparison (REITs only)")
    peers_latest = peers[(peers["fiscal_year"] == LATEST_YEAR) & (peers["security_type"] == "REIT")]
    display_cols = ["ticker", "sector", "enterprise_value_mm", "ffo_mm", "nav_mm", "ev_ebitda_multiple", "p_ffo_multiple", "p_nav_multiple", "pe_multiple", "pb_multiple"]
    peer_display = peers_latest[display_cols].copy()
    peer_display["pe_multiple"] = "N/A (not meaningful for REITs)"
    peer_display["pb_multiple"] = "N/A (not meaningful for REITs)"
    st.dataframe(peer_display.set_index("ticker"), use_container_width=True)
    st.caption("P/E and P/B are not meaningful REIT valuation metrics and are marked N/A; P/FFO and P/NAV are the REIT-appropriate multiples.")

    st.plotly_chart(price_chart(reit_ticker), use_container_width=True)


# --------------------------------------------------------------------------
# View 4: Portfolio Lab
# --------------------------------------------------------------------------
elif view == "Portfolio Lab":
    st.title("Portfolio Lab")
    st.caption(DISCLAIMER + " Results are backtested against this project's synthetic monthly price history.")

    screen = build_factor_screen(processed)
    portfolios = build_default_portfolios(processed, screen)

    all_tickers = sorted(master["ticker"])
    default_selection = sorted(portfolios["model_portfolio"].keys())
    selected = st.multiselect("Securities", all_tickers, default=default_selection)

    if not selected:
        st.info("Select at least one security.")
        st.stop()

    st.markdown("#### Weights")
    if st.button("Reset to equal weight"):
        for t in selected:
            st.session_state[f"w_{t}"] = round(100 / len(selected), 2)

    cols = st.columns(min(5, len(selected)))
    raw_weights = {}
    for i, t in enumerate(selected):
        default_w = round(100 / len(selected), 2)
        raw_weights[t] = cols[i % len(cols)].number_input(t, 0.0, 100.0, st.session_state.get(f"w_{t}", default_w), 1.0, key=f"w_{t}")

    total_pct = sum(raw_weights.values())
    st.caption(f"Total: {total_pct:.1f}% (must equal 100%)")
    weights = {t: w / 100 for t, w in raw_weights.items() if w > 0}

    try:
        if abs(total_pct - 100.0) > 0.01:
            raise WeightValidationError(f"Weights sum to {total_pct:.1f}%, not 100%.")
        validate_weights(weights)
    except WeightValidationError as e:
        st.error(f"Cannot run analytics: {e}")
        st.stop()

    colA, colB = st.columns(2)
    benchmark_choice = colA.selectbox("Benchmark", ["Equal-weight (all 20)", "Custom (market-cap-weighted, all 20)"])
    rebalance = colB.selectbox("Rebalance assumption", ["monthly", "none"], format_func=lambda x: "Monthly rebalance" if x == "monthly" else "Buy & hold (no rebalance)")
    benchmark_weights = portfolios["equal_weight_benchmark"] if benchmark_choice.startswith("Equal") else portfolios["custom_benchmark"]

    pa = compute_portfolio_analytics(processed, weights, benchmark_weights, rebalance=rebalance)
    m = pa["metrics"]

    st.markdown("#### Risk / Return")
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Annualized return", f"{m.annualized_return:.1%}")
    c2.metric("Annualized volatility", f"{m.annualized_volatility:.1%}")
    c3.metric("Sharpe ratio", f"{m.sharpe_ratio:.2f}")
    c4.metric("Max drawdown", f"{m.max_drawdown:.1%}")
    c5.metric("Beta vs. benchmark", f"{m.beta:.2f}")
    st.caption(f"Active return (annualized) vs. benchmark: {m.active_return_annualized:+.1%}. Dividend income per USD 100 invested over the period: USD {pa['dividend_income_per_100']:.2f}. Turnover vs. an equal-weight starting point: {pa['turnover_vs_equal_weight']:.1%}.")

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=pa["portfolio_returns"].cumulative_growth.index, y=pa["portfolio_returns"].cumulative_growth.values, name="Portfolio"))
    fig.add_trace(go.Scatter(x=pa["benchmark_returns"].cumulative_growth.index, y=pa["benchmark_returns"].cumulative_growth.values, name="Benchmark"))
    fig.update_layout(title="Cumulative Growth of $1 (simulated, backtested)", height=380, margin=dict(t=40))
    st.plotly_chart(fig, use_container_width=True)

    colC, colD = st.columns(2)
    with colC:
        st.markdown("#### Sector Concentration")
        sc = pa["sector_concentration"]
        fig2 = go.Figure(go.Pie(labels=sc.index, values=sc.values))
        fig2.update_layout(height=350, margin=dict(t=20))
        st.plotly_chart(fig2, use_container_width=True)
    with colD:
        st.markdown("#### Security Concentration")
        sec_conc = security_concentration(weights)
        fig3 = go.Figure(go.Bar(x=sec_conc.index, y=sec_conc.values))
        fig3.update_layout(height=350, margin=dict(t=20), yaxis_tickformat=".0%")
        st.plotly_chart(fig3, use_container_width=True)

    st.markdown("#### Contribution to Return / Risk")
    contrib_df = pd.DataFrame({"contribution_to_return": pa["contribution_to_return"], "contribution_to_risk": pa["contribution_to_risk"]})
    st.dataframe(contrib_df.style.format("{:.2%}").background_gradient(cmap="RdYlGn", axis=0), use_container_width=True)


# --------------------------------------------------------------------------
# View 5: Scenario Lab
# --------------------------------------------------------------------------
elif view == "Scenario Lab":
    st.title("Scenario Lab")
    st.caption(DISCLAIMER)

    focus = st.selectbox("Focus", ["Single security"] + ["Model Portfolio (top factor-ranked names)"])

    preset = st.radio("Start from preset", ["Bear", "Base", "Bull", "Custom"], horizontal=True, index=1)
    preset_map = {"Bear": BEAR, "Base": BASE, "Bull": BULL}
    start = preset_map.get(preset, BASE)

    st.markdown("#### Scenario assumption deltas")
    c1, c2, c3 = st.columns(3)
    revenue_growth_delta = c1.slider("Revenue growth delta", -0.10, 0.10, start.revenue_growth_delta, 0.01)
    ebitda_margin_delta = c2.slider("EBITDA margin delta", -0.10, 0.10, start.ebitda_margin_delta, 0.01)
    discount_rate_delta = c3.slider("Discount / interest rate delta", -0.03, 0.03, start.discount_rate_delta, 0.0025)
    c4, c5, c6 = st.columns(3)
    terminal_growth_delta = c4.slider("Terminal growth delta", -0.02, 0.02, start.terminal_growth_delta, 0.0025)
    cap_rate_delta = c5.slider("Cap rate delta", -0.02, 0.02, start.cap_rate_delta, 0.0025)
    leverage_delta_pct = c6.slider("Leverage (net debt) % change", -0.20, 0.20, start.leverage_delta_pct, 0.01)
    sector_price_shock_pct = st.slider("Sector price shock %", -0.30, 0.30, start.sector_price_shock_pct, 0.01)

    custom_scenario = Scenario(
        name="Custom", revenue_growth_delta=revenue_growth_delta, ebitda_margin_delta=ebitda_margin_delta,
        discount_rate_delta=discount_rate_delta, terminal_growth_delta=terminal_growth_delta,
        cap_rate_delta=cap_rate_delta, leverage_delta_pct=leverage_delta_pct, sector_price_shock_pct=sector_price_shock_pct,
    )

    if focus == "Single security":
        ticker = st.selectbox("Security", sorted(master["ticker"]))
        is_reit = ticker in REIT_TICKERS
        scenarios = [BEAR, BASE, BULL, custom_scenario]

        if is_reit:
            rrow = reit_annual[reit_annual["ticker"] == ticker].sort_values("fiscal_year").iloc[-1]
            rows = []
            for s in scenarios:
                r = apply_scenario_to_reit(rrow["property_value_mm"], rrow["noi_mm"], rrow["net_debt_mm"], rrow["shares_outstanding_mm"], s)
                rows.append(r)
            df = pd.DataFrame(rows)
            base_nav = df[df["scenario"] == "Base"]["nav_per_share"].iloc[0]
            df["nav_per_share_change_vs_base"] = df["nav_per_share"] - base_nav
            df["nav_per_share_pct_change_vs_base"] = df["nav_per_share"] / base_nav - 1
            st.dataframe(df.set_index("scenario"), use_container_width=True)
            fig = go.Figure(go.Bar(x=df["scenario"], y=df["nav_per_share"]))
            fig.update_layout(title=f"{ticker} NAV/share by scenario", height=380, margin=dict(t=40))
            st.plotly_chart(fig, use_container_width=True)
        else:
            base_assumptions = build_dcf_assumptions_from_financials(ticker, master, annual)
            rows = []
            for s in scenarios:
                adj = apply_scenario_to_dcf(base_assumptions, s)
                result = run_dcf(adj)
                rows.append({"scenario": s.name, "value_per_share": result.value_per_share, "enterprise_value": result.enterprise_value, "equity_value": result.equity_value})
            df = pd.DataFrame(rows)
            base_val = df[df["scenario"] == "Base"]["value_per_share"].iloc[0]
            df["value_per_share_change_vs_base"] = df["value_per_share"] - base_val
            df["value_per_share_pct_change_vs_base"] = df["value_per_share"] / base_val - 1
            st.dataframe(df.set_index("scenario"), use_container_width=True)
            fig = go.Figure(go.Bar(x=df["scenario"], y=df["value_per_share"]))
            fig.update_layout(title=f"{ticker} DCF value/share by scenario", height=380, margin=dict(t=40))
            st.plotly_chart(fig, use_container_width=True)

    else:
        screen = build_factor_screen(processed)
        portfolios = build_default_portfolios(processed, screen)
        weights = portfolios["model_portfolio"]

        val_impact = portfolio_valuation_scenario_impact(processed, weights)
        custom_row = None
        reit_tickers_in_port = [t for t in weights if t in REIT_TICKERS]
        non_reit_in_port = [t for t in weights if t not in REIT_TICKERS]
        weighted_change = 0.0
        for t in non_reit_in_port:
            base_assumptions = build_dcf_assumptions_from_financials(t, master, annual)
            base_val = run_dcf(base_assumptions).value_per_share
            adj_val = run_dcf(apply_scenario_to_dcf(base_assumptions, custom_scenario)).value_per_share
            weighted_change += weights[t] * (adj_val / base_val - 1)
        for t in reit_tickers_in_port:
            rrow = reit_annual[reit_annual["ticker"] == t].sort_values("fiscal_year").iloc[-1]
            base_nav = reit_nav(rrow["property_value_mm"], rrow["net_debt_mm"], rrow["shares_outstanding_mm"]).nav_per_share
            custom_r = apply_scenario_to_reit(rrow["property_value_mm"], rrow["noi_mm"], rrow["net_debt_mm"], rrow["shares_outstanding_mm"], custom_scenario)
            weighted_change += weights[t] * (custom_r["nav_per_share"] / base_nav - 1)

        custom_row = pd.DataFrame([{"scenario": "Custom", "weighted_avg_fair_value_change_pct": weighted_change}])
        combined = pd.concat([val_impact, custom_row], ignore_index=True)

        st.markdown("#### Model Portfolio: Weighted-Average Fair-Value Change by Scenario")
        st.dataframe(combined.set_index("scenario").style.format("{:+.1%}"), use_container_width=True)
        fig = go.Figure(go.Bar(x=combined["scenario"], y=combined["weighted_avg_fair_value_change_pct"]))
        fig.update_layout(title="Model Portfolio fair-value change vs. Base", height=380, margin=dict(t=40), yaxis_tickformat=".0%")
        st.plotly_chart(fig, use_container_width=True)

        st.markdown("#### Sector Price-Shock Stress Test")
        shock_df = portfolio_sector_shock_impact(processed, weights)
        custom_shock = custom_scenario.sector_price_shock_pct * shock_df["shocked_sector_weight"].iloc[0]
        shock_custom_row = pd.DataFrame([{
            "scenario": "Custom", "shocked_sector": shock_df["shocked_sector"].iloc[0],
            "shocked_sector_weight": shock_df["shocked_sector_weight"].iloc[0],
            "sector_price_shock_pct": custom_scenario.sector_price_shock_pct,
            "portfolio_market_value_impact_pct": custom_shock,
        }])
        shock_combined = pd.concat([shock_df, shock_custom_row], ignore_index=True)
        st.dataframe(shock_combined.set_index("scenario"), use_container_width=True)
        st.caption(f"Shocks the portfolio's largest sector weight ({shock_df['shocked_sector'].iloc[0]}) by the scenario's sector price shock %, holding other sectors flat.")
