"""Excel research pack and Markdown research-note writers.

Every sheet is written from a pandas DataFrame the caller computed with
`src/analytics_pipeline.py` -- this module only formats and lays out what it
is given (freeze panes, autofilter, column widths, number formats,
conditional formatting, charts). It hard-codes no analytical results.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.worksheet.worksheet import Worksheet
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.chart import BarChart, LineChart, PieChart, Reference

HEADER_FILL = PatternFill(start_color="1F4E79", end_color="1F4E79", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True)
TITLE_FONT = Font(bold=True, size=14, color="1F4E79")
SUBTITLE_FONT = Font(italic=True, size=10, color="595959")
NOTE_FONT = Font(italic=True, size=9, color="808080")

PCT_KEYWORDS = (
    "_pct", "occupancy", "cap_rate", "discount_rate", "terminal_growth",
    "_growth", "growth_", "_margin", "margin_", "dividend_yield", "upside",
    "_return", "return_", "weight", "concentration", "change_pct", "shock",
)
CURRENCY_KEYWORDS = (
    "_mm", "value", "price", "nav_per_share", "_income", "debt", "cash",
    "equity", "assets", "liabilities", "capex", "noi", "ffo", "affo", "fcf",
)
MULTIPLE_KEYWORDS = ("multiple",)
DECIMAL_KEYWORDS = ("beta", "sharpe", "zscore", "z_score", "score", "drawdown")


def _infer_number_format(col: str) -> str | None:
    c = col.lower()
    if any(k in c for k in MULTIPLE_KEYWORDS):
        return '0.00"x"'
    if any(k in c for k in PCT_KEYWORDS):
        return "0.0%"
    if any(k in c for k in CURRENCY_KEYWORDS):
        return "#,##0.00"
    if any(k in c for k in DECIMAL_KEYWORDS):
        return "0.00"
    return None


def write_table(
    ws: Worksheet, df: pd.DataFrame, start_row: int = 1, start_col: int = 1,
    freeze: bool = True, autofilter: bool = True, colorscale_cols: tuple[str, ...] = (),
) -> int:
    """Write a DataFrame with a styled header at (start_row, start_col).
    Returns the row index immediately after the table (for stacking sheets)."""
    n_rows, n_cols = df.shape
    for j, col in enumerate(df.columns):
        cell = ws.cell(row=start_row, column=start_col + j, value=str(col))
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center")

    for i in range(n_rows):
        for j, col in enumerate(df.columns):
            val = df.iat[i, j]
            if pd.isna(val):
                val = None
            elif hasattr(val, "item"):
                val = val.item()
            cell = ws.cell(row=start_row + 1 + i, column=start_col + j, value=val)
            fmt = _infer_number_format(str(col))
            if fmt and isinstance(val, (int, float)):
                cell.number_format = fmt

    for j, col in enumerate(df.columns):
        col_letter = get_column_letter(start_col + j)
        max_len = max([len(str(col))] + [len(str(v)) for v in df[col].astype(str).values[:200]])
        ws.column_dimensions[col_letter].width = min(max(max_len + 2, 10), 42)

    end_row = start_row + n_rows
    end_col = start_col + n_cols - 1
    if autofilter and n_rows > 0:
        ws.auto_filter.ref = f"{get_column_letter(start_col)}{start_row}:{get_column_letter(end_col)}{end_row}"
    if freeze:
        ws.freeze_panes = ws.cell(row=start_row + 1, column=start_col)

    for col_name in colorscale_cols:
        if col_name not in df.columns:
            continue
        col_idx = start_col + list(df.columns).index(col_name)
        col_letter = get_column_letter(col_idx)
        rng = f"{col_letter}{start_row + 1}:{col_letter}{end_row}"
        ws.conditional_formatting.add(
            rng,
            ColorScaleRule(
                start_type="min", start_color="F8696B",
                mid_type="percentile", mid_value=50, mid_color="FFEB84",
                end_type="max", end_color="63BE7B",
            ),
        )

    return end_row + 2


def write_title(ws: Worksheet, text: str, row: int, col: int = 1, subtitle: str | None = None) -> int:
    ws.cell(row=row, column=col, value=text).font = TITLE_FONT
    next_row = row + 1
    if subtitle:
        ws.cell(row=next_row, column=col, value=subtitle).font = SUBTITLE_FONT
        next_row += 1
    return next_row + 1


DISCLAIMER = (
    "Simulated analysis. All data in this workbook is synthetic, generated by this "
    "project for demonstration purposes. It does not reference any real company, "
    "security, or market. Nothing here is investment advice or a real research report."
)


# --------------------------------------------------------------------------
# Sheet builders
# --------------------------------------------------------------------------
def build_research_summary_sheet(ws: Worksheet, summary: dict, top_ideas: pd.DataFrame) -> None:
    row = write_title(ws, "Investment Research & Portfolio Analytics Workbench", 1, subtitle="Research Summary")
    ws.cell(row=row, column=1, value=DISCLAIMER).font = NOTE_FONT
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    row += 2

    stats = pd.DataFrame(
        [{"metric": k, "value": v} for k, v in summary.items()]
    )
    row = write_table(ws, stats, start_row=row, freeze=False, autofilter=False)

    ws.cell(row=row, column=1, value="Top-Ranked Ideas (current factor weights)").font = Font(bold=True, size=12)
    row += 1
    write_table(ws, top_ideas, start_row=row, freeze=False, colorscale_cols=("composite_score",))


def build_company_financials_sheet(ws: Worksheet, annual: pd.DataFrame) -> None:
    write_title(ws, "Company Financials (Annual)", 1, subtitle="All 20 securities, synthetic, USD millions unless noted")
    write_table(ws, annual.sort_values(["ticker", "fiscal_year"]), start_row=3)


def build_reit_metrics_sheet(ws: Worksheet, reit_annual: pd.DataFrame, nav_summary: pd.DataFrame) -> None:
    row = write_title(ws, "REIT Metrics", 1, subtitle="NOI, FFO, AFFO, occupancy, and cap rate history for the 5 REITs. Not applicable to non-REIT securities.")
    row = write_table(ws, reit_annual.sort_values(["ticker", "fiscal_year"]), start_row=row)
    ws.cell(row=row, column=1, value="Latest NAV and Cap-Rate Cross-Check").font = Font(bold=True, size=12)
    row += 1
    write_table(ws, nav_summary, start_row=row, freeze=False, colorscale_cols=("nav_per_share",))


def build_dcf_valuation_sheet(ws: Worksheet, dcf_all: pd.DataFrame, sensitivity: pd.DataFrame, sensitivity_ticker: str) -> int:
    row = write_title(ws, "DCF Valuation", 1, subtitle="Base, Bear, and Bull discounted cash flow value per share for every non-REIT security. Not hard-coded -- recomputed from src/valuation.py + src/scenarios.py against each security's own financials.")
    row = write_table(ws, dcf_all, start_row=row, colorscale_cols=("upside_vs_current_price",))

    ws.cell(row=row, column=1, value=f"Sensitivity: {sensitivity_ticker} value/share -- discount rate (rows) x terminal growth (cols)").font = Font(bold=True, size=12)
    row += 1
    sens = sensitivity.reset_index()
    sens.columns = ["discount_rate"] + [f"g={c:.2%}" for c in sensitivity.columns]
    write_table(ws, sens, start_row=row, freeze=False, autofilter=False)
    return row


def build_comparables_sheet(ws: Worksheet, comps: pd.DataFrame, peer_multiples_latest: pd.DataFrame) -> None:
    row = write_title(ws, "Comparable Companies", 1, subtitle="Peer-group multiples and implied per-share value for every security. Peer groups: Company / REIT / Financial-Infrastructure.")
    row = write_table(ws, comps, start_row=row, colorscale_cols=("implied_value_per_share",))
    ws.cell(row=row, column=1, value="Underlying Peer Multiples (latest fiscal year)").font = Font(bold=True, size=12)
    row += 1
    write_table(ws, peer_multiples_latest, start_row=row, freeze=False)


def build_portfolio_analytics_sheet(
    ws: Worksheet, weights: pd.DataFrame, metrics: pd.DataFrame, sector_conc: pd.DataFrame,
    contribution: pd.DataFrame, growth_series: pd.DataFrame, other: dict,
) -> None:
    row = write_title(ws, "Portfolio Analytics", 1, subtitle="Model Portfolio (top factor-ranked names) vs. an equal-weight benchmark. Backtested against this project's synthetic monthly price history -- not real trading performance.")
    ws.cell(row=row, column=1, value="Model Portfolio Weights").font = Font(bold=True, size=12)
    row += 1
    row = write_table(ws, weights, start_row=row, freeze=False, autofilter=False, colorscale_cols=("weight",))

    ws.cell(row=row, column=1, value="Risk / Return Metrics (Model Portfolio vs. Equal-Weight Benchmark)").font = Font(bold=True, size=12)
    row += 1
    row = write_table(ws, metrics, start_row=row, freeze=False, autofilter=False)

    other_row = row
    for label, value in other.items():
        ws.cell(row=other_row, column=1, value=label)
        ws.cell(row=other_row, column=2, value=value)
        other_row += 1
    row = other_row + 1

    ws.cell(row=row, column=1, value="Sector Concentration").font = Font(bold=True, size=12)
    row += 1
    sector_start = row
    row = write_table(ws, sector_conc, start_row=row, freeze=False, autofilter=False, colorscale_cols=("weight",))

    ws.cell(row=row, column=1, value="Contribution to Return / Risk").font = Font(bold=True, size=12)
    row += 1
    row = write_table(ws, contribution, start_row=row, freeze=False, autofilter=False)

    ws.cell(row=row, column=1, value="Cumulative Growth of $1").font = Font(bold=True, size=12)
    row += 1
    growth_start = row
    row = write_table(ws, growth_series, start_row=row, freeze=False, autofilter=False)

    # Line chart: portfolio vs benchmark cumulative growth
    n = len(growth_series)
    chart = LineChart()
    chart.title = "Cumulative Growth of $1: Portfolio vs. Benchmark (simulated)"
    chart.y_axis.title = "Growth of $1"
    chart.x_axis.title = "Month"
    data = Reference(ws, min_col=2, max_col=3, min_row=growth_start, max_row=growth_start + n)
    cats = Reference(ws, min_col=1, min_row=growth_start + 1, max_row=growth_start + n)
    chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    chart.width, chart.height = 22, 10
    ws.add_chart(chart, f"H{growth_start}")

    # Pie chart: sector weights
    n_sec = len(sector_conc)
    pie = PieChart()
    pie.title = "Sector Weights (Model Portfolio)"
    data = Reference(ws, min_col=2, min_row=sector_start, max_row=sector_start + n_sec)
    cats = Reference(ws, min_col=1, min_row=sector_start + 1, max_row=sector_start + n_sec)
    pie.add_data(data, titles_from_data=True)
    pie.set_categories(cats)
    pie.width, pie.height = 14, 10
    ws.add_chart(pie, f"H{sector_start}")


def build_scenario_analysis_sheet(
    ws: Worksheet, dcf_scenarios: pd.DataFrame, reit_scenarios: pd.DataFrame,
    portfolio_valuation_impact: pd.DataFrame, portfolio_sector_shock: pd.DataFrame,
    featured_company: str, featured_reit: str,
) -> None:
    row = write_title(ws, "Scenario Analysis", 1, subtitle="Bull / Base / Bear assumption shocks applied to valuation and portfolio outputs, with absolute values and change vs. Base.")

    ws.cell(row=row, column=1, value=f"DCF Scenarios: {featured_company}").font = Font(bold=True, size=12)
    row += 1
    dcf_start = row
    row = write_table(ws, dcf_scenarios, start_row=row, freeze=False, autofilter=False)

    ws.cell(row=row, column=1, value=f"REIT NAV Scenarios: {featured_reit}").font = Font(bold=True, size=12)
    row += 1
    row = write_table(ws, reit_scenarios, start_row=row, freeze=False, autofilter=False)

    ws.cell(row=row, column=1, value="Model Portfolio: Weighted-Average Fair-Value Change by Scenario").font = Font(bold=True, size=12)
    row += 1
    impact_start = row
    row = write_table(ws, portfolio_valuation_impact, start_row=row, freeze=False, autofilter=False)

    ws.cell(row=row, column=1, value="Model Portfolio: Largest-Sector Price-Shock Stress Test").font = Font(bold=True, size=12)
    row += 1
    row = write_table(ws, portfolio_sector_shock, start_row=row, freeze=False, autofilter=False)

    n = len(dcf_scenarios)
    chart = BarChart()
    chart.type = "col"
    chart.title = f"{featured_company} DCF Value/Share by Scenario"
    data = Reference(ws, min_col=list(dcf_scenarios.columns).index("value_per_share") + 1,
                      max_col=list(dcf_scenarios.columns).index("value_per_share") + 1,
                      min_row=dcf_start, max_row=dcf_start + n)
    cats = Reference(ws, min_col=list(dcf_scenarios.columns).index("scenario") + 1,
                      min_row=dcf_start + 1, max_row=dcf_start + n)
    chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    chart.width, chart.height = 16, 9
    ws.add_chart(chart, f"H{dcf_start}")

    n2 = len(portfolio_valuation_impact)
    chart2 = BarChart()
    chart2.type = "col"
    chart2.title = "Model Portfolio: Weighted-Avg Fair-Value Change vs. Base"
    data2 = Reference(ws, min_col=2, max_col=2, min_row=impact_start, max_row=impact_start + n2)
    cats2 = Reference(ws, min_col=1, min_row=impact_start + 1, max_row=impact_start + n2)
    chart2.add_data(data2, titles_from_data=True)
    chart2.set_categories(cats2)
    chart2.width, chart2.height = 16, 9
    ws.add_chart(chart2, f"H{dcf_start + 18}")


def build_data_quality_sheet(ws: Worksheet, dq: pd.DataFrame) -> None:
    row = write_title(ws, "Data Quality", 1, subtitle="Issues independently detected by src/ingest.py -- not a list of known answers, a rule-based scan of the processed tables.")
    if dq.empty:
        ws.cell(row=row, column=1, value="No data-quality issues detected.")
        return
    summary = dq.groupby("issue_type").size().reset_index(name="count")
    ws.cell(row=row, column=1, value="Issues by Type").font = Font(bold=True, size=12)
    row += 1
    row = write_table(ws, summary, start_row=row, freeze=False, autofilter=False)
    ws.cell(row=row, column=1, value="Full Issue Log").font = Font(bold=True, size=12)
    row += 1
    write_table(ws, dq, start_row=row)


def build_assumptions_sheet(ws: Worksheet, data_dictionary: pd.DataFrame, assumptions: pd.DataFrame) -> None:
    row = write_title(ws, "Assumptions and Data Dictionary", 1, subtitle="Default assumptions used across the workbook, and a description of every transformed field.")
    ws.cell(row=row, column=1, value="Default Assumptions").font = Font(bold=True, size=12)
    row += 1
    row = write_table(ws, assumptions, start_row=row, freeze=False, autofilter=False)
    ws.cell(row=row, column=1, value="Data Dictionary").font = Font(bold=True, size=12)
    row += 1
    write_table(ws, data_dictionary, start_row=row)


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------
def build_excel_pack(output_path: Path, sheets_data: dict) -> None:
    wb = Workbook()
    wb.remove(wb.active)

    ws = wb.create_sheet("Research Summary")
    build_research_summary_sheet(ws, sheets_data["summary"], sheets_data["top_ideas"])

    ws = wb.create_sheet("Company Financials")
    build_company_financials_sheet(ws, sheets_data["company_financials_annual"])

    ws = wb.create_sheet("REIT Metrics")
    build_reit_metrics_sheet(ws, sheets_data["reit_financials_annual"], sheets_data["reit_nav_summary"])

    ws = wb.create_sheet("DCF Valuation")
    build_dcf_valuation_sheet(ws, sheets_data["dcf_all"], sheets_data["dcf_sensitivity"], sheets_data["sensitivity_ticker"])

    ws = wb.create_sheet("Comparable Companies")
    build_comparables_sheet(ws, sheets_data["comps"], sheets_data["peer_multiples_latest"])

    ws = wb.create_sheet("Portfolio Analytics")
    build_portfolio_analytics_sheet(
        ws, sheets_data["portfolio_weights"], sheets_data["portfolio_metrics"],
        sheets_data["sector_concentration"], sheets_data["contribution"],
        sheets_data["growth_series"], sheets_data["portfolio_other"],
    )

    ws = wb.create_sheet("Scenario Analysis")
    build_scenario_analysis_sheet(
        ws, sheets_data["dcf_scenarios"], sheets_data["reit_scenarios"],
        sheets_data["portfolio_valuation_impact"], sheets_data["portfolio_sector_shock"],
        sheets_data["sensitivity_ticker"], sheets_data["featured_reit"],
    )

    ws = wb.create_sheet("Data Quality")
    build_data_quality_sheet(ws, sheets_data["data_quality"])

    ws = wb.create_sheet("Assumptions and Data Dictionary")
    build_assumptions_sheet(ws, sheets_data["data_dictionary"], sheets_data["assumptions"])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)


def write_research_note_file(output_path: Path, markdown_text: str) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown_text)
